use_frameworks!

abstract_target 'Pod' do

 pod 'TBDropboxKit', :path => '../'

    target 'TBDropboxKit_Example' do
        target 'TBDropboxKit_Tests' do
            inherit! :search_paths
        end
    end
    target 'TBDropboxKitMac-Example' do
        target 'TBDropboxKitMac-ExampleTests' do
            inherit! :search_paths
        end
    end
end
